language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - postgresql

# command to install dependencies
install: "pip install -r requirements.pip"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script: "python manage.py test"